/* ============================================================================
 * nse_proxy.c - Napoleon Script Extender, proxy-DLL edition.
 *
 * Ships as dinput8.dll in the game root. Windows loads a DLL from the
 * application directory before the system one, so Napoleon loads US, we forward
 * the five real exports to the system dinput8.dll, and meanwhile we get native
 * code running INSIDE the process before main() - which means our hooks are in
 * place before Lua even initialises. No injector, no attach timing race.
 *
 * WHY dinput8: Napoleon.exe imports DINPUT8.dll (verified from its import
 * table: ADVAPI32, binkw32, COMDLG32, d3d9, d3dx9d_40, DINPUT8, DSOUND, ...),
 * it has only five exports, and it is not a protected KnownDLL, so the
 * app-directory override reliably works. tbb/binkw32/mss32 also sit in the game
 * root but have far larger (and C++-mangled) export surfaces.
 *
 * THE POINT: a named pipe that evaluates arbitrary Lua IN THE RUNNING GAME, on
 * the game's own thread, in whichever lua_State you name. Iterate without
 * restarting.
 *
 * ---------------------------------------------------------------------------
 * WHAT IS VERIFIED, AND HOW
 *
 *   Napoleon.exe is 32-bit (machine 0x014C), ImageBase 0x00400000, and
 *   statically links the SAME Lua 5.1 build as Empire: Total War. The ten C API
 *   addresses below were located by tools/find_lua_api.rb, which masks
 *   relocation-dependent bytes out of Empire's known function bodies and
 *   searches Napoleon's .text for the remainder. Each matched exactly once, AND
 *   all ten landed at identical relative offsets from lua_getfield - the same
 *   object file, relocated by 0xE1B70. Ten functions agreeing on ten offsets is
 *   the proof; a single unique hit would not have been.
 *
 *   Run `ruby tools/find_lua_api.rb --verify` to re-derive these. If a patch
 *   moves them, that is the tool that tells you the new values.
 *
 * WHAT IS *NOT* VERIFIED
 *
 *   Everything above was established statically, from the binary and the
 *   shipped packs. Nothing here has been run against a live Napoleon process.
 *   Treat the first launch as a bring-up: check nse_log.txt, expect the
 *   prologue guard to refuse rather than to corrupt, and read the "bring-up"
 *   section of the README before assuming a silent failure is a crash.
 *
 *   The battle-state binding in particular is a heuristic (see g_battleL). If
 *   it never fires, `@battle` reports that plainly instead of guessing.
 * ========================================================================= */

#include <windows.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <setjmp.h>
#include <stdlib.h>

/* ---- the exact build these addresses were derived from -------------------
 *
 * Every address below is specific to ONE Napoleon.exe. Steam updates, regional
 * builds and the non-Steam release all move them. Without this check a user on
 * a different build gets only "prologue mismatch", which is correct but tells
 * them nothing about why.
 *
 * TimeDateStamp and SizeOfImage come straight from the PE header, cost two
 * memory reads, and cannot be fooled by a renamed file the way a filename or a
 * version resource can.
 *
 *   Napoleon.exe  FileVersion 1.3.0.0  (ProductVersion 3.0.1.0)
 *   17,895,424 bytes
 *   SHA256 44880EC1770F600163A336EEC83B4366901484C5CCEEC83DC326E2932F02A054
 */
#define NSE_TARGET_TIMESTAMP   0x645E917F   /* 2023-05-12 19:20:31 UTC */
#define NSE_TARGET_SIZEOFIMAGE 0x014EB000
#define NSE_TARGET_DESC        "Napoleon.exe 1.3.0.0 (17,895,424 bytes)"

/* ---- Lua 5.1 C API, Napoleon.exe, ImageBase 0x00400000 -------------------
 * generated by tools/find_lua_api.rb --verify                              */
#define A_lua_getfield       0x00FE8F90
#define A_lua_gettop         0x00FE9070
#define A_lua_pcall          0x00FE93C0
#define A_lua_pushcclosure   0x00FE9460
#define A_lua_pushlstring    0x00FE9560
#define A_lua_setfield       0x00FE9990
#define A_lua_settop         0x00FE9AD0
#define A_lua_tolstring      0x00FE9C40
#define A_lua_type           0x00FE9DA0
#define A_luaL_loadbuffer    0x00FEA6C0

#define LUA_GLOBALSINDEX   (-10002)
#define LUA_TNIL             0
#define LUA_TSTRING          4
#define LUA_TTABLE           5
#define LUA_TFUNCTION        6

/* Both lua_getfield and lua_setfield begin with the same five bytes:
 *   83 EC 08   sub esp,8
 *   53         push ebx
 *   56         push esi
 * Whole instructions, none position-dependent, so one trampoline shape serves
 * both. Confirmed present at both Napoleon addresses by find_lua_api.rb, and
 * checked again at runtime before anything is patched. */
#define STEAL 5
static const unsigned char kProlog[STEAL] = { 0x83,0xEC,0x08,0x53,0x56 };

typedef void* lua_State;
typedef int (__cdecl *lua_CFunction)(lua_State*);

typedef void (__cdecl *fn_getfield)(lua_State*, int, const char*);
typedef void (__cdecl *fn_setfield)(lua_State*, int, const char*);
typedef void (__cdecl *fn_settop)(lua_State*, int);
typedef int  (__cdecl *fn_gettop)(lua_State*);
typedef int  (__cdecl *fn_type)(lua_State*, int);
typedef void (__cdecl *fn_pushcclosure)(lua_State*, lua_CFunction, int);
typedef void (__cdecl *fn_pushlstring)(lua_State*, const char*, size_t);
typedef const char* (__cdecl *fn_tolstring)(lua_State*, int, size_t*);
typedef int  (__cdecl *fn_loadbuffer)(lua_State*, const char*, size_t, const char*);
typedef int  (__cdecl *fn_pcall)(lua_State*, int, int, int);

static struct {
    fn_getfield     getfield;
    fn_setfield     setfield;
    fn_settop       settop;
    fn_gettop       gettop;
    fn_type         type;
    fn_pushcclosure pushcclosure;
    fn_pushlstring  pushlstring;
    fn_tolstring    tolstring;
    fn_loadbuffer   loadbuffer;
    fn_pcall        pcall;
} L_;

static DWORD      g_delta  = 0;
static lua_State* g_campL  = NULL;   /* campaign scripting state              */
static lua_State* g_uiL    = NULL;   /* campaign UI ROOT (not per-component)  */
static lua_State* g_battleL= NULL;   /* battle script state, if it binds      */

/* Napoleon runs the UI in SEPARATE lua_States - roughly one per UI component -
 * and the UI API (UIComponent, Component, Address) exists ONLY there. So
 * panelmanager cannot work from the campaign state.
 *
 * TWO states receive the CampaignUI global: a minimal one and the real UI root,
 * which ALSO receives Component. CampaignUI arrives first, so: collect the
 * candidates, then promote whichever later receives Component.
 *
 * Deliberately NOT tracking every state that gets Component: there are ~100 of
 * them, they are created and destroyed as panels come and go, and holding a
 * pointer to one is a use-after-free. */
#define CAND_MAX 4
static lua_State* g_cand[CAND_MAX];
static int        g_cand_n = 0;

/* ---- crash-guard state (declared early: several paths use it) ------------ */
static volatile LONG  g_guard_armed    = 0;
static jmp_buf        g_guard_jmp;                 /* longjmp target: pump()      */
static jmp_buf        g_prot_jmp;                  /* longjmp target: NSE_Protect */
static volatile LONG  g_guard_use_prot = 0;
static volatile DWORD g_guard_code     = 0;
static PVOID          g_veh            = NULL;

/* ---- pipe <-> game-thread handoff.
 * The pipe thread NEVER touches Lua. It fills g_req, raises g_pending and
 * waits; the pump, running on the game thread inside a Lua hook, executes it
 * and raises g_done. This is the single most important safety property here:
 * lua_State is not thread-safe, and the engine's allocator and GC assume
 * single-threaded access. */
#define REQ_MAX 8192
#define RES_MAX 8192
static volatile LONG g_pending = 0;
static volatile LONG g_done    = 0;
static char g_req[REQ_MAX];
static char g_res[RES_MAX];

/* Where the log goes. Resolved once, on first use.
 *
 * The default Steam library lives under Program Files (x86), which is NOT
 * user-writable. There, fopen("nse_log.txt","a") fails and the extender would
 * run perfectly while producing no log at all - and the documented diagnosis
 * ("no log means the DLL never loaded") would be exactly wrong, sending people
 * to debug a problem they do not have.
 *
 * So: try the game folder, and fall back to the game's own settings directory
 * under %APPDATA%, which Napoleon already writes to and which is always
 * writable for the user running it. */
static char  g_logpath[MAX_PATH] = {0};
static LONG  g_logpath_done = 0;

static void resolve_logpath(void) {
    if (InterlockedCompareExchange(&g_logpath_done, 1, 0) != 0) return;

    /* first choice: beside the game, where people expect to find it */
    FILE* probe = fopen("nse_log.txt", "a");
    if (probe) {
        fclose(probe);
        strcpy(g_logpath, "nse_log.txt");
        return;
    }

    /* fallback: %APPDATA%\The Creative Assembly\Napoleon\nse_log.txt
     * The directory already exists on any machine that has run the game once;
     * create it anyway in case this is a first launch. */
    const char* appdata = getenv("APPDATA");
    if (appdata) {
        char dir[MAX_PATH];
        _snprintf(dir, MAX_PATH - 1, "%s\\The Creative Assembly", appdata);
        dir[MAX_PATH - 1] = 0; CreateDirectoryA(dir, NULL);
        _snprintf(dir, MAX_PATH - 1, "%s\\The Creative Assembly\\Napoleon", appdata);
        dir[MAX_PATH - 1] = 0; CreateDirectoryA(dir, NULL);
        _snprintf(g_logpath, MAX_PATH - 1, "%s\\nse_log.txt", dir);
        g_logpath[MAX_PATH - 1] = 0;
        FILE* f = fopen(g_logpath, "a");
        if (f) { fclose(f); return; }
    }
    /* Nowhere to write. Leave the path empty; logging becomes a no-op rather
     * than a crash, and the pipe still answers "@nat states". */
    g_logpath[0] = 0;
}

static void nse_log(const char* fmt, ...) {
    char buf[1024];
    va_list ap; va_start(ap, fmt);
    _vsnprintf(buf, sizeof(buf)-1, fmt, ap); buf[sizeof(buf)-1] = 0;
    va_end(ap);
    resolve_logpath();
    if (!g_logpath[0]) return;
    /* Opened and closed per line on purpose: anything logged is on disk before
     * the next statement runs, which is the only reliable way to get data out
     * of a session that is about to die. */
    FILE* f = fopen(g_logpath, "a");
    if (f) { fprintf(f, "%s\n", buf); fclose(f); }
}

/* ======================= trampoline construction ========================= *
 * Built as raw bytes at runtime rather than as a naked function: no inline-asm
 * syntax or symbol-decoration surprises, and total control over the layout.
 *
 *   9C                    pushfd
 *   60                    pushad
 *   8D 44 24 24           lea eax,[esp+0x24]   ; -> original stack frame
 *   50                    push eax             ; handler(stk)
 *   B8 <handler>          mov eax,<handler>
 *   FF D0                 call eax
 *   83 C4 04              add esp,4
 *   61                    popad
 *   9D                    popfd
 *   <stolen bytes>
 *   68 <ret>              push <site+steal>    ; push/ret avoids computing a
 *   C3                    ret                  ; relative displacement
 *
 * After pushfd(4)+pushad(0x20)=0x24, [esp+0x24] is the original [esp+0], so the
 * handler receives {retaddr, arg1, arg2, arg3, ...}.
 * ========================================================================= */
static void* make_tramp(unsigned char* site, void* handler, int stealLen) {
    unsigned char* t = (unsigned char*)VirtualAlloc(NULL, 64,
                            MEM_COMMIT|MEM_RESERVE, PAGE_EXECUTE_READWRITE);
    if (!t) return NULL;
    int i = 0;
    t[i++] = 0x9C;
    t[i++] = 0x60;
    t[i++] = 0x8D; t[i++] = 0x44; t[i++] = 0x24; t[i++] = 0x24;
    t[i++] = 0x50;
    t[i++] = 0xB8; *(void**)(t+i) = handler;         i += 4;
    t[i++] = 0xFF; t[i++] = 0xD0;
    t[i++] = 0x83; t[i++] = 0xC4; t[i++] = 0x04;
    t[i++] = 0x61;
    t[i++] = 0x9D;
    memcpy(t+i, site, stealLen);                     i += stealLen;
    t[i++] = 0x68; *(void**)(t+i) = (void*)(site + stealLen); i += 4;
    t[i++] = 0xC3;
    return t;
}

/* Patch `site` with E9 rel32 -> tramp. The prologue is verified FIRST and the
 * hook refused on a mismatch. This is what turns "a patch moved the function"
 * from silent memory corruption into a line in the log. It is not optional. */
static int install_hook_ex(DWORD staticAddr, void* handler,
                           const unsigned char* expect, int stealLen) {
    unsigned char* site = (unsigned char*)(staticAddr + g_delta);
    if (memcmp(site, expect, stealLen) != 0) {
        nse_log("[nse] REFUSING to hook %p: prologue mismatch (%02X %02X %02X %02X %02X)",
                site, site[0], site[1], site[2], site[3], site[4]);
        nse_log("[nse]   expected %02X %02X %02X %02X %02X",
                expect[0], expect[1], expect[2], expect[3], expect[4]);
        nse_log("[nse]   These addresses were derived for %s.", NSE_TARGET_DESC);
        nse_log("[nse]   Recover with: ruby tools/find_lua_api.rb --verify");
        return 0;
    }
    void* tramp = make_tramp(site, handler, stealLen);
    if (!tramp) { nse_log("[nse] trampoline alloc failed"); return 0; }

    DWORD old;
    if (!VirtualProtect(site, stealLen, PAGE_EXECUTE_READWRITE, &old)) return 0;
    site[0] = 0xE9;
    *(DWORD*)(site+1) = (DWORD)tramp - ((DWORD)site + 5);
    VirtualProtect(site, stealLen, old, &old);
    FlushInstructionCache(GetCurrentProcess(), site, stealLen);
    nse_log("[nse] hooked %p -> tramp %p (steal %d)", site, tramp, stealLen);
    return 1;
}

static int install_hook(DWORD a, void* h) { return install_hook_ex(a, h, kProlog, STEAL); }

/* ============================ native functions =========================== */

static void push_str(lua_State* L, const char* s) { L_.pushlstring(L, s, strlen(s)); }

static int __cdecl nse_ping(lua_State* L) { push_str(L, "pong"); return 1; }

static int __cdecl nse_version(lua_State* L) {
    push_str(L, "NSE proxy 0.1 (Lua 5.1, Napoleon: Total War, 32-bit)");
    return 1;
}

/* NSE_Protect(fn) -> "true" | "NATIVE_FAULT:0x..." | "LUA_ERROR:..."
 *
 * Runs a Lua function with the crash guard ARMED. Without this, only REPL evals
 * are protected - and mod code lives in event handlers, which the engine calls
 * directly.
 *
 * `pcall` DOES NOT PROTECT YOU. The engine's condition functions are native C
 * that dereference their arguments without validating, so a wrong arity or a
 * wrong-scoped context is a hard access violation, not a catchable Lua error.
 * pcall catches Lua errors only.
 *
 * Wrap anything that touches conditions / effect / game_interface:
 *
 *     scripting.AddEventCallBack("FactionTurnStart", function(context)
 *         NSE_Protect(function() ... end)
 *     end)
 *
 * Its own jmp_buf, because a handler can run while a REPL eval is in flight. */
static volatile LONG g_prot_busy = 0;

static int __cdecl nse_protect(lua_State* L) {
    if (L_.type(L, 1) != LUA_TFUNCTION) {
        push_str(L, "NSE_Protect: expected a function");
        return 1;
    }
    /* No nesting: an inner fault would clobber the outer jmp_buf. Degrade to a
     * plain pcall rather than refusing outright. */
    if (InterlockedCompareExchange(&g_prot_busy, 1, 0) != 0) {
        int rc0 = L_.pcall(L, 0, 0, 0);
        push_str(L, rc0 ? "LUA_ERROR (nested)" : "true");
        return 1;
    }

    if (setjmp(g_prot_jmp) != 0) {          /* arrived here from the VEH */
        char buf[96];
        _snprintf(buf, sizeof(buf)-1, "NATIVE_FAULT:0x%08lX", g_guard_code);
        buf[sizeof(buf)-1] = 0;
        nse_log("[nse] NSE_Protect caught a native fault (0x%08lX)", g_guard_code);
        g_guard_armed = 0;
        InterlockedExchange(&g_prot_busy, 0);
        L_.settop(L, 0);
        push_str(L, buf);
        return 1;
    }

    g_guard_use_prot = 1;
    g_guard_armed    = 1;
    int rc = L_.pcall(L, 0, 0, 0);
    g_guard_armed    = 0;
    g_guard_use_prot = 0;
    InterlockedExchange(&g_prot_busy, 0);

    if (rc != 0) {
        const char* e = L_.tolstring(L, -1, NULL);
        char buf[512];
        _snprintf(buf, sizeof(buf)-1, "LUA_ERROR:%s", e ? e : "?");
        buf[sizeof(buf)-1] = 0;
        L_.settop(L, 0);
        push_str(L, buf);
    } else {
        push_str(L, "true");
    }
    return 1;
}

/* ===================== live memory inspection ============================ *
 * Turns NSE into a debugger for the running game: read the engine's own
 * structures while a campaign is loaded, instead of inferring them from a crash
 * dump afterwards. Napoleon's campaign object graph is undocumented, and this
 * is how you map it.
 *
 * String in, string out. Only tolstring and pushlstring are bound, not
 * tonumber/pushnumber - and lua_Number is a double, awkward to push from here.
 * Lua's own tonumber() handles the conversion on the other side.
 *
 * Every read is bounds-checked with VirtualQuery FIRST. A bad address returns
 * "UNREADABLE" rather than faulting: this exists for poking at unknown
 * structures, so it must never be able to take the game down. */
static int mem_readable(const void* p, size_t n) {
    MEMORY_BASIC_INFORMATION mbi;
    if (!p) return 0;
    if (VirtualQuery(p, &mbi, sizeof(mbi)) == 0) return 0;
    if (mbi.State != MEM_COMMIT) return 0;
    if (mbi.Protect & PAGE_GUARD) return 0;
    DWORD prot = mbi.Protect & 0xFF;
    if (prot == PAGE_NOACCESS || prot == PAGE_EXECUTE) return 0;
    size_t avail = (size_t)(((char*)mbi.BaseAddress + mbi.RegionSize) - (char*)p);
    return avail >= n;
}

/* accepts "0x14A4174", "14A4174" (hex assumed) or "#12345" for decimal */
static DWORD parse_addr(const char* s) {
    if (!s) return 0;
    while (*s == ' ') s++;
    if (*s == '#') return (DWORD)strtoul(s + 1, NULL, 10);
    if (s[0] == '0' && (s[1] == 'x' || s[1] == 'X')) return (DWORD)strtoul(s + 2, NULL, 16);
    return (DWORD)strtoul(s, NULL, 16);
}

/* NSE_Delta() -> "0x3F0000" : add to a static (Ghidra) address for a live one */
static int __cdecl nse_delta(lua_State* L) {
    char b[32]; _snprintf(b, sizeof(b)-1, "0x%lX", (unsigned long)g_delta); b[31]=0;
    push_str(L, b); return 1;
}

static int __cdecl nse_readint(lua_State* L) {
    DWORD a = parse_addr(L_.tolstring(L, 1, NULL));
    if (!mem_readable((void*)a, 4)) { push_str(L, "UNREADABLE"); return 1; }
    char b[32]; _snprintf(b, sizeof(b)-1, "%ld", (long)*(int*)a); b[31]=0;
    push_str(L, b); return 1;
}

static int __cdecl nse_readfloat(lua_State* L) {
    DWORD a = parse_addr(L_.tolstring(L, 1, NULL));
    if (!mem_readable((void*)a, 4)) { push_str(L, "UNREADABLE"); return 1; }
    char b[48]; _snprintf(b, sizeof(b)-1, "%f", (double)*(float*)a); b[47]=0;
    push_str(L, b); return 1;
}

/* NSE_ReadBytes("0x...", "#16") -> "56 8B F9 ..." (max 64) */
static int __cdecl nse_readbytes(lua_State* L) {
    DWORD a = parse_addr(L_.tolstring(L, 1, NULL));
    int   n = (int)parse_addr(L_.tolstring(L, 2, NULL));
    if (n <= 0 || n > 64) n = 16;
    if (!mem_readable((void*)a, (size_t)n)) { push_str(L, "UNREADABLE"); return 1; }
    char b[256]; int w = 0;
    for (int i = 0; i < n && w < (int)sizeof(b)-4; i++)
        w += _snprintf(b+w, sizeof(b)-1-w, "%02X ", ((unsigned char*)a)[i]);
    b[w > 0 ? w-1 : 0] = 0;
    push_str(L, b); return 1;
}

/* NSE_ReadStr("0x...", "#64") -> the C string there, or "UNREADABLE" */
static int __cdecl nse_readstr(lua_State* L) {
    DWORD a = parse_addr(L_.tolstring(L, 1, NULL));
    int   n = (int)parse_addr(L_.tolstring(L, 2, NULL));
    if (n <= 0 || n > 255) n = 64;
    if (!mem_readable((void*)a, 1)) { push_str(L, "UNREADABLE"); return 1; }
    char b[256]; int i = 0;
    for (; i < n; i++) {
        if (!mem_readable((void*)(a+i), 1)) break;
        char c = ((char*)a)[i];
        if (c == 0) break;
        b[i] = (c >= 32 && c < 127) ? c : '.';
    }
    b[i] = 0;
    push_str(L, b); return 1;
}

/* NSE_Log("text") -> writes to nse_log.txt immediately.
 *
 * The point is CRASH SURVIVAL: nse_log opens, writes and closes per line, so
 * anything logged is on disk before the next statement runs. That makes it the
 * only reliable way to get data out of a session that is about to die - the
 * pipe cannot help, because you cannot hand-time a request into the window
 * between campaign-script init and a fault. */
static int __cdecl nse_luaLog(lua_State* L) {
    const char* s = L_.tolstring(L, 1, NULL);
    nse_log("[lua] %s", s ? s : "(nil)");
    push_str(L, "ok");
    return 1;
}

/* ===================== NSE_Say: campaign -> UI bridge =====================
 * Lets a MOD talk to the player on its own, rather than only when a human runs
 * nse.ps1 -Say.
 *
 * The problem it solves: mod code runs in the CAMPAIGN lua_State, but
 * panelmanager - the only way to put text on screen - exists solely in the UI
 * state. They are separate lua_States and neither can call the other.
 *
 * Same queue-and-pump shape as the pipe: NSE_Say() stores the text, and the
 * next time a Lua hook fires we evaluate the panel call IN THE UI STATE.
 * Nothing crosses a thread boundary (both states live on the game thread).
 *
 * Napoleon's own UI does exactly this. Extracted from data.pack:
 *   ui\common ui\dialogue_box.luac  requires 'Utilities'.Require('PanelManager')
 *                                   and exposes Initialise(txt, ok_cb, cancel_cb)
 *   ui\panelmanager.luac            requires 'CoreUtils', exposes OpenPanel,
 *                                   IsPanelOpen, ClosePanel, and knows
 *                                   'dialogue_box'
 * Both module spellings are tried, because the two shipped scripts disagree.
 */
#define SAY_MAX 2048
static char          g_say[SAY_MAX];
static volatile LONG g_say_pending = 0;
static int           g_say_retry   = 0;

static int __cdecl nse_say(lua_State* L) {
    const char* s = L_.tolstring(L, 1, NULL);
    if (!s) { push_str(L, "NSE_Say: expected a string"); return 1; }
    if (g_say_pending) { push_str(L, "busy"); return 1; }   /* one at a time */
    _snprintf(g_say, SAY_MAX - 1, "%s", s);
    g_say[SAY_MAX - 1] = 0;
    g_say_pending = 1;
    push_str(L, "queued");
    return 1;
}

static void say_pump(void) {
    /* Re-entrancy guard - NOT optional. This runs inside the lua_getfield hook
     * and then calls Lua itself, which calls lua_getfield, which re-enters
     * here. Without the guard a nested loadbuffer corrupts the outer one's
     * stack and every attempt fails to compile. */
    static volatile LONG busy = 0;
    if (!g_say_pending || !g_uiL) return;
    if (InterlockedCompareExchange(&busy, 1, 0) != 0) return;

    g_say_pending = 0;      /* clear BEFORE running: a failure must not retry
                             * on every single hook call */

    char esc[SAY_MAX * 2]; int w = 0;
    for (int i = 0; g_say[i] && w < (int)sizeof(esc) - 8; i++) {
        char c = g_say[i];
        if (c == '\\' || c == '\'') { esc[w++] = '\\'; esc[w++] = c; }
        else if (c == '\n') { esc[w++] = '\\'; esc[w++] = 'n'; }
        else if (c == '\r') { }
        else esc[w++] = c;
    }
    esc[w] = 0;

    /* DEFER if a panel is already up. The game's own turn-start messages use
     * the SAME dialogue_box panel, so opening ours on top either loses our text
     * or interrupts theirs. Ask panelmanager first and retry later. */
    char chunk[SAY_MAX * 2 + 768];
    _snprintf(chunk, sizeof(chunk) - 1,
        "local pm "
        "for _,m in ipairs({'Utilities','CoreUtils'}) do "
        "  local ok,u = pcall(require, m) "
        "  if ok and type(u)=='table' and u.Require then "
        "    local ok2,p = pcall(u.Require, 'panelmanager') "
        "    if not (ok2 and type(p)=='table') then ok2,p = pcall(u.Require,'PanelManager') end "
        "    if ok2 and type(p)=='table' then pm = p break end "
        "  end "
        "end "
        "if type(pm)~='table' or not pm.OpenPanel then return 'nopm' end "
        "local busy = false "
        "for _,p in ipairs({'dialogue_box','event_message','message_scroll'}) do "
        "  local o,r = pcall(pm.IsPanelOpen, p) if o and r then busy = true end end "
        "if busy then return 'busy' end "
        "pcall(pm.OpenPanel,'dialogue_box',false,'Initialise','%s') return 'shown'",
        esc);
    chunk[sizeof(chunk) - 1] = 0;

    lua_State* L = g_uiL;
    int top = L_.gettop(L);
    if (L_.loadbuffer(L, chunk, strlen(chunk), "=nse_say") == 0) {
        if (L_.pcall(L, 0, 1, 0) == 0) {
            const char* r = L_.tolstring(L, -1, NULL);
            if (r && r[0] == 'b') {                 /* "busy" - screen occupied */
                if (++g_say_retry < 600) g_say_pending = 1;
                else nse_log("[nse] NSE_Say gave up after %d retries", g_say_retry);
            } else {
                if (r && r[0] == 'n') nse_log("[nse] NSE_Say: panelmanager not reachable from this state");
                g_say_retry = 0;
            }
        } else {
            const char* e = L_.tolstring(L, -1, NULL);
            nse_log("[nse] NSE_Say failed: %s", e ? e : "?");
        }
    } else {
        /* Log the ACTUAL compiler error and the chunk. "compile failed" with no
         * detail is the same fail-quietly trap this engine keeps setting. */
        const char* e = L_.tolstring(L, -1, NULL);
        nse_log("[nse] NSE_Say compile failed: %s", e ? e : "?");
        nse_log("[nse]   chunk was: %.300s", chunk);
    }
    L_.settop(L, top);
    InterlockedExchange(&busy, 0);
}

static const struct { const char* name; lua_CFunction fn; } kNatives[] = {
    { "NSE_Say",       nse_say       },
    { "NSE_Log",       nse_luaLog    },
    { "NSE_Protect",   nse_protect   },
    { "NSE_Delta",     nse_delta     },
    { "NSE_ReadInt",   nse_readint   },
    { "NSE_ReadFloat", nse_readfloat },
    { "NSE_ReadBytes", nse_readbytes },
    { "NSE_ReadStr",   nse_readstr   },
    { "NSE_Ping",      nse_ping      },
    { "NSE_Version",   nse_version   },
    { NULL, NULL }
};

/* Register through LUA_GLOBALSINDEX. NOT via _G - in the campaign state those
 * are different tables, and a _G-based check reports failure on a registration
 * that actually works. If you go looking for NSE_Ping with rawget(_G,...) you
 * will find nil and conclude, wrongly, that nothing was registered. */
static void register_natives(lua_State* L) {
    for (int i = 0; kNatives[i].name; i++) {
        L_.pushcclosure(L, kNatives[i].fn, 0);
        L_.setfield(L, LUA_GLOBALSINDEX, kNatives[i].name);
    }
    nse_log("[nse] registered %d native function(s) into state %p",
            (int)(sizeof(kNatives)/sizeof(kNatives[0])) - 1, L);
}

/* ===================== crash guard ======================================= *
 * A vectored exception handler runs BEFORE normal SEH unwinding, so we can
 * intercept an access violation and longjmp back into pump() to report it as a
 * string instead of losing the session.
 *
 * HONEST TRADE-OFF: longjmping out of a fault deep inside engine code can leave
 * game state inconsistent - a lock unreleased, an allocation half-finished. It
 * converts a CERTAIN crash into a PROBABLE recovery, which is the right trade
 * for a development tool but is not "safe" in any strong sense. If the game
 * behaves oddly after a guard trip, restart it.
 *
 * (VEH rather than __try/__except because compiler SEH support is unreliable on
 * the 32-bit MinGW ABI this builds against.)
 */
static int safe_rd(DWORD addr, DWORD* out) {
    MEMORY_BASIC_INFORMATION mbi;
    if (!addr || VirtualQuery((void*)addr, &mbi, sizeof(mbi)) == 0) return 0;
    if (mbi.State != MEM_COMMIT || (mbi.Protect & PAGE_GUARD)) return 0;
    DWORD p = mbi.Protect & 0xFF;
    if (p == PAGE_NOACCESS || p == PAGE_EXECUTE) return 0;
    *out = *(DWORD*)addr;
    return 1;
}

/* Logs the full context of ANY access violation in Napoleon.exe, not just ones
 * during our own evals. Windows Error Reporting gives you a fault offset; this
 * gives EIP, every register, the faulting address, the read/write direction and
 * the nearby stack - from inside the process, before the crash completes.
 *
 * It does NOT interfere: it observes, then returns CONTINUE_SEARCH so the
 * game's own handling proceeds exactly as before. */
static void report_fault(EXCEPTION_POINTERS* ep) {
    EXCEPTION_RECORD* er = ep->ExceptionRecord;
    CONTEXT*          cx = ep->ContextRecord;
    DWORD eip = cx->Eip;

    nse_log("!!! FAULT %08lX at EIP=%08lX  (static %08lX)",
            (unsigned long)er->ExceptionCode, (unsigned long)eip,
            (unsigned long)(eip - g_delta));

    if (er->ExceptionCode == EXCEPTION_ACCESS_VIOLATION && er->NumberParameters >= 2) {
        const char* what = er->ExceptionInformation[0] == 0 ? "READ from"
                         : er->ExceptionInformation[0] == 1 ? "WRITE to"
                         : "EXECUTE at";
        nse_log("    %s %08lX", what, (unsigned long)er->ExceptionInformation[1]);
    }
    nse_log("    EAX=%08lX EBX=%08lX ECX=%08lX EDX=%08lX",
            (unsigned long)cx->Eax, (unsigned long)cx->Ebx,
            (unsigned long)cx->Ecx, (unsigned long)cx->Edx);
    nse_log("    ESI=%08lX EDI=%08lX EBP=%08lX ESP=%08lX",
            (unsigned long)cx->Esi, (unsigned long)cx->Edi,
            (unsigned long)cx->Ebp, (unsigned long)cx->Esp);

    /* Bytes at EIP: confirms which instruction actually faulted, independent of
     * WER's offset. */
    DWORD v;
    char b[64]; int w = 0;
    for (int i = 0; i < 12 && w < (int)sizeof(b) - 4; i++) {
        if (!safe_rd(eip + i, &v)) break;
        w += _snprintf(b + w, sizeof(b) - 1 - w, "%02X ", *(unsigned char*)(eip + i));
    }
    b[w] = 0;
    nse_log("    bytes at EIP: %s", b);

    /* Stack words that look like return addresses into Napoleon.exe - a poor
     * man's call stack, but enough to identify the caller. Static addresses, so
     * they can be pasted straight into Ghidra. */
    char s[600]; w = 0;
    DWORD lo = (DWORD)g_delta + 0x400000, hi = lo + 0x1500000;
    for (int i = 0; i < 48 && w < (int)sizeof(s) - 20; i++) {
        DWORD sp = cx->Esp + i * 4, val;
        if (!safe_rd(sp, &val)) break;
        if (val > lo && val < hi)
            w += _snprintf(s + w, sizeof(s) - 1 - w, "%08lX(s=%08lX) ",
                           (unsigned long)val, (unsigned long)(val - g_delta));
    }
    s[w] = 0;
    nse_log("    return-address candidates: %s", s);
}

static LONG CALLBACK nse_veh(EXCEPTION_POINTERS* ep) {
    DWORD code = ep->ExceptionRecord->ExceptionCode;

    /* Observe every genuine fault, whether or not our guard is armed. Logged
     * first, so the record exists even if the process dies immediately after. */
    if (code == EXCEPTION_ACCESS_VIOLATION) {
        static LONG reported = 0;
        if (InterlockedCompareExchange(&reported, 1, 0) == 0) report_fault(ep);
    }

    /* Only step in for OUR evaluation, and only for genuine faults - never
     * interfere with exceptions the game raises during normal operation. */
    if (!g_guard_armed) return EXCEPTION_CONTINUE_SEARCH;
    if (code != EXCEPTION_ACCESS_VIOLATION &&
        code != EXCEPTION_ILLEGAL_INSTRUCTION &&
        code != EXCEPTION_PRIV_INSTRUCTION &&
        code != EXCEPTION_INT_DIVIDE_BY_ZERO) return EXCEPTION_CONTINUE_SEARCH;

    g_guard_code  = code;
    g_guard_armed = 0;
    if (g_guard_use_prot) longjmp(g_prot_jmp, 1);   /* back into NSE_Protect */
    longjmp(g_guard_jmp, 1);                        /* back into pump()      */
    return EXCEPTION_CONTINUE_SEARCH;               /* not reached           */
}

/* ===================== autoexec ========================================== *
 * Run nse_autoexec.lua (game folder) in a freshly-acquired campaign state.
 *
 * Without this, every Lua-side thing you set up - event handlers, helpers, the
 * mod itself - would have to be re-sent by hand after every campaign load,
 * because a new campaign means a new lua_State with none of it. This is what
 * makes NSE usable for an actual mod rather than just probing. */
static void run_autoexec(lua_State* L) {
    FILE* f = fopen("nse_autoexec.lua", "rb");
    if (!f) return;                       /* optional file - absent is fine */
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (n <= 0 || n > 1024*1024) { fclose(f); nse_log("[nse] autoexec: bad size"); return; }
    char* buf = (char*)malloc((size_t)n + 1);
    if (!buf) { fclose(f); return; }
    size_t got = fread(buf, 1, (size_t)n, f);
    fclose(f);
    buf[got] = 0;

    int top = L_.gettop(L);
    int rc = L_.loadbuffer(L, buf, got, "=nse_autoexec");
    if (rc != 0) {
        const char* e = L_.tolstring(L, -1, NULL);
        nse_log("[nse] autoexec COMPILE error: %s", e ? e : "?");
    } else {
        rc = L_.pcall(L, 0, 0, 0);
        if (rc != 0) {
            const char* e = L_.tolstring(L, -1, NULL);
            nse_log("[nse] autoexec RUNTIME error: %s", e ? e : "?");
        } else {
            nse_log("[nse] autoexec ran OK (%ld bytes)", n);
        }
    }
    L_.settop(L, top);
    free(buf);
}

/* The campaign state is detected the moment `conditions` is assigned, but the
 * scripting layer does not exist yet at that point - so running the autoexec
 * there finds nothing to hook and silently does nothing.
 *
 * NAPOLEON DIFFERS FROM EMPIRE HERE. Empire exposes a global `events` table.
 * Napoleon's campaign scripting goes through a MODULE:
 *
 *     local scripting = require "EpisodicScripting"
 *     scripting.AddEventCallBack("FactionTurnStart", handler)
 *
 * (from data\campaigns\eur_napoleon\scripting.lua, shipped in plain text), and
 * EpisodicScripting itself does `core.Require "data.events"` for the event
 * tables. So the readiness signal is package.loaded.EpisodicScripting becoming
 * a table, not a global appearing.
 *
 * We walk package -> loaded -> EpisodicScripting with lua_getfield, which is
 * cheap. Empire's global `events` is accepted too, so this still works if a
 * campaign script sets one up.
 *
 * Re-entrancy matters: we call lua_getfield from INSIDE the lua_getfield hook,
 * which would recurse forever without the guard. */
static LONG g_autoexec_pending = 0;

static int state_ready(lua_State* L) {
    int top = L_.gettop(L);
    int ready = 0;

    L_.getfield(L, LUA_GLOBALSINDEX, "package");
    if (L_.type(L, -1) == LUA_TTABLE) {
        L_.getfield(L, -1, "loaded");
        if (L_.type(L, -1) == LUA_TTABLE) {
            L_.getfield(L, -1, "EpisodicScripting");
            if (L_.type(L, -1) == LUA_TTABLE) ready = 1;
        }
    }
    L_.settop(L, top);
    if (ready) return 1;

    L_.getfield(L, LUA_GLOBALSINDEX, "events");
    ready = (L_.type(L, -1) == LUA_TTABLE);
    L_.settop(L, top);
    return ready;
}

static void try_autoexec(void) {
    static volatile LONG busy = 0;
    static DWORD tick = 0;
    if (!g_autoexec_pending || !g_campL) return;
    /* lua_getfield is extremely hot. Polling a three-deep table walk on every
     * single call would be a measurable tax on the game for no benefit, so
     * throttle - the window we are waiting for is hundreds of milliseconds
     * wide, not microseconds. */
    if ((++tick & 0xFF) != 0) return;
    if (InterlockedCompareExchange(&busy, 1, 0) != 0) return;

    if (state_ready(g_campL)) {
        g_autoexec_pending = 0;
        nse_log("[nse] scripting layer is up - running autoexec");
        run_autoexec(g_campL);
    }
    InterlockedExchange(&busy, 0);
}

/* ================================ the pump =============================== *
 * Runs on the GAME thread (called from a Lua-API hook). Drains one queued
 * request, evaluates it in the requested state, and stores the result. */
static void pump(void) {
    static volatile LONG reentry = 0;
    if (!g_pending) return;
    if (InterlockedCompareExchange(&reentry, 1, 0) != 0) return; /* no recursion */

    const char* src = g_req;
    lua_State*  L   = g_campL;
    const char* which = "campaign";

    /* "@ui " -> the campaign UI root state, the only place the UI API lives.
     * "@battle " -> the battle script state, if one has been bound. */
    if (g_req[0] == '@') {
        if (strncmp(g_req, "@ui", 3) == 0) {
            const char* p = g_req + 3; if (*p == ' ') p++;
            src = p; L = g_uiL; which = "campaign UI";
        } else if (strncmp(g_req, "@battle", 7) == 0) {
            const char* p = g_req + 7; if (*p == ' ') p++;
            src = p; L = g_battleL; which = "battle";
        }
    }
    if (!L) {
        _snprintf(g_res, RES_MAX-1,
            "no %s lua_State bound yet. The campaign state exists only once a "
            "campaign is loaded; the UI root once its panels are up; the battle "
            "state only inside a battle (and its binding is heuristic - see "
            "nse_log.txt).", which);
        g_res[RES_MAX-1] = 0;
        g_pending = 0; g_done = 1;
        InterlockedExchange(&reentry, 0);
        return;
    }

    int top = L_.gettop(L);

    /* Log the command BEFORE running it. If it kills the game anyway (the guard
     * cannot catch everything), nse_log.txt still names the exact culprit. */
    nse_log("[nse] eval(%s): %s", which, src);

    if (setjmp(g_guard_jmp) != 0) {
        _snprintf(g_res, RES_MAX-1,
            "NATIVE CRASH (0x%08lX) caught - the call faulted inside engine code. "
            "pcall cannot catch this. The game survived, but its state may be "
            "unreliable; restart if it misbehaves.", g_guard_code);
        g_res[RES_MAX-1] = 0;
        nse_log("[nse] GUARD TRIPPED 0x%08lX on: %s", g_guard_code, src);
        L_.settop(L, top);
        g_pending = 0; g_done = 1;
        InterlockedExchange(&reentry, 0);
        return;
    }
    g_guard_armed = 1;

    int rc = L_.loadbuffer(L, src, strlen(src), "=nse");
    if (rc != 0) {
        const char* e = L_.tolstring(L, -1, NULL);
        _snprintf(g_res, RES_MAX-1, "compile error: %s", e ? e : "?");
    } else {
        rc = L_.pcall(L, 0, 1, 0);
        if (rc != 0) {
            const char* e = L_.tolstring(L, -1, NULL);
            _snprintf(g_res, RES_MAX-1, "runtime error: %s", e ? e : "?");
        } else {
            /* tolstring coerces numbers too; nil and other types report their
             * type rather than coming back as an empty string. */
            const char* s = L_.tolstring(L, -1, NULL);
            if (s) _snprintf(g_res, RES_MAX-1, "%s", s);
            else   _snprintf(g_res, RES_MAX-1, "(%s)",
                             L_.type(L,-1) == LUA_TNIL ? "nil" : "non-string value");
        }
    }
    g_res[RES_MAX-1] = 0;

    g_guard_armed = 0;      /* disarm as soon as our own eval is done, so the
                             * handler never intercepts the game's own
                             * exceptions during normal play */
    L_.settop(L, top);      /* always restore the stack we borrowed */
    g_pending = 0;
    g_done    = 1;
    InterlockedExchange(&reentry, 0);
}

/* =============================== handlers ================================ */

/* Candidate sentinels for the battle script state.
 *
 * HEURISTIC, and labelled as such. Napoleon registers 218 battle commands
 * through the registrar at 0x0059EB40 (see tools/dump_script_api.rb), but that
 * registrar stores them into its own lists rather than calling lua_setfield
 * directly, so static analysis cannot prove the names land as globals. If they
 * do, one of these fires and @battle works. If they do not, nothing binds and
 * @battle says so plainly - it never guesses at a state.
 *
 * `nse.ps1 -Native states` prints what actually bound, which is how you find
 * the real sentinel if these are wrong. */
static const char* kBattleSentinels[] = {
    "BattleDetails", "CameraZoomTo", "AddUnitsToGroup", "BroadsideMouseEvent", NULL
};

/* stk = { retaddr, L, idx, k }
 *
 * The campaign guard keys on L, NOT on a "have I registered yet" flag. Going
 * back to the menu and loading another campaign builds a NEW lua_State; with a
 * one-shot boolean we would keep pointing g_campL at the old, freed state and
 * write into freed memory on the next eval. Comparing L means a new state is
 * detected and re-registered automatically. */
static void __cdecl on_setfield(DWORD* stk) {
    if ((int)stk[2] == LUA_GLOBALSINDEX && stk[3]) {
        const char* k = (const char*)stk[3];
        lua_State* L = (lua_State*)stk[1];

        /* Collect CampaignUI-bearing candidates. Exact match, not a 4-byte
         * prefix: "Camp" would also hit CampaignName and friends. */
        if (strcmp(k, "CampaignUI") == 0) {
            int known = 0;
            for (int i = 0; i < g_cand_n; i++) if (g_cand[i] == L) { known = 1; break; }
            if (!known && g_cand_n < CAND_MAX) {
                g_cand[g_cand_n++] = L;
                if (!g_uiL) g_uiL = L;      /* provisional until one proves better */
                nse_log("[nse] CampaignUI candidate: %p", L);
            }
        }
        /* Promote a candidate that ALSO has the Component API - that one is the
         * real UI root. Deliberately not tracking every Component-bearing
         * state: there are ~100, they are per-component and transient, and
         * holding pointers to those is a use-after-free. */
        else if (strcmp(k, "Component") == 0) {
            for (int i = 0; i < g_cand_n; i++) {
                if (g_cand[i] == L && g_uiL != L) {
                    g_uiL = L;
                    nse_log("[nse] UI root confirmed (has Component): %p", L);
                    break;
                }
            }
        }
        /* "cond..." -> this L is the campaign scripting state. */
        else if (k[0]=='c' && k[1]=='o' && k[2]=='n' && k[3]=='d') {
            if (L != g_campL) {
                g_campL = L;
                nse_log("[nse] campaign state (re)acquired: %p (key '%s')", L, k);
                register_natives(L);
                g_autoexec_pending = 1;   /* deferred until scripting is up */
            }
        }
        else if (!g_battleL) {
            for (int i = 0; kBattleSentinels[i]; i++) {
                if (strcmp(k, kBattleSentinels[i]) == 0) {
                    g_battleL = L;
                    nse_log("[nse] battle state bound: %p (sentinel '%s')", L, k);
                    register_natives(L);
                    break;
                }
            }
        }
    }
    pump();
}

/* lua_getfield is extremely hot - it runs for effectively every global and
 * table read - which makes it a reliable heartbeat for draining queued work
 * even when the player is idle on the campaign map. */
static void __cdecl on_getfield(DWORD* stk) {
    (void)stk;
    try_autoexec();
    say_pump();
    pump();
}

/* ============================== pipe server ============================== */

/* "@nat ..." commands need no lua_State at all, so they work at the main menu
 * and during loading - which is exactly when you most want to ask what has
 * bound so far. */
static int native_cmd(const char* c) {
    if (strncmp(c, "states", 6) == 0) {
        resolve_logpath();
        _snprintf(g_res, RES_MAX-1,
            "delta=0x%lX\ncampaign=%p\nui_root=%p (%d CampaignUI candidate(s))\nbattle=%p\n"
            "autoexec=%s\nlog=%s",
            (unsigned long)g_delta, g_campL, g_uiL, g_cand_n, g_battleL,
            g_autoexec_pending ? "waiting for the scripting layer" : "done or not started",
            g_logpath[0] ? g_logpath : "(nowhere writable - logging disabled)");
    } else if (strncmp(c, "version", 7) == 0) {
        _snprintf(g_res, RES_MAX-1, "NSE proxy 0.1 for Napoleon: Total War (32-bit, Lua 5.1)");
    } else {
        _snprintf(g_res, RES_MAX-1, "unknown native command. try: states | version");
    }
    g_res[RES_MAX-1] = 0;
    return 1;
}

static DWORD WINAPI pipe_thread(LPVOID unused) {
    (void)unused;
    for (;;) {
        HANDLE h = CreateNamedPipeA("\\\\.\\pipe\\nse",
                        PIPE_ACCESS_DUPLEX,
                        PIPE_TYPE_MESSAGE|PIPE_READMODE_MESSAGE|PIPE_WAIT,
                        1, RES_MAX, REQ_MAX, 0, NULL);
        if (h == INVALID_HANDLE_VALUE) { Sleep(1000); continue; }
        if (!ConnectNamedPipe(h, NULL) && GetLastError() != ERROR_PIPE_CONNECTED) {
            CloseHandle(h); continue;
        }
        DWORD n = 0;
        if (ReadFile(h, g_req, REQ_MAX-1, &n, NULL) && n > 0) {
            g_req[n] = 0;
            g_res[0] = 0;
            g_done   = 0;

            if (strncmp(g_req, "@nat", 4) == 0) {
                const char* p = g_req + 4; if (*p == ' ') p++;
                native_cmd(p);
            } else {
                g_pending = 1;
                /* wait for the game thread to drain it */
                for (int i = 0; i < 1000 && !g_done; i++) Sleep(5);
                if (!g_done) {
                    g_pending = 0;
                    _snprintf(g_res, RES_MAX-1,
                        "timeout - no Lua activity on the game thread to pump the "
                        "request. Is the game paused at a loading screen?");
                    g_res[RES_MAX-1] = 0;
                }
            }
            DWORD w = 0;
            WriteFile(h, g_res, (DWORD)strlen(g_res), &w, NULL);
            FlushFileBuffers(h);
        }
        DisconnectNamedPipe(h);
        CloseHandle(h);
    }
    return 0;
}

/* ================================= init ================================== */
static DWORD WINAPI init_thread(LPVOID unused) {
    (void)unused;
    HMODULE base = GetModuleHandleA(NULL);
    g_delta = (DWORD)base - 0x00400000;
    nse_log("[nse] ---- start ---- base=%p delta=0x%X", base, g_delta);

    /* Identify the host build BEFORE touching anything. This is advisory: a
     * mismatch is reported and startup continues, because the prologue guard is
     * the thing that actually prevents damage. But it turns a later
     * "prologue mismatch" from a mystery into a one-line diagnosis. */
    {
        unsigned char* img = (unsigned char*)base;
        DWORD peoff = *(DWORD*)(img + 0x3C);
        DWORD stamp = *(DWORD*)(img + peoff + 8);
        DWORD sizeimg = *(DWORD*)(img + peoff + 24 + 56);
        if (stamp == NSE_TARGET_TIMESTAMP && sizeimg == NSE_TARGET_SIZEOFIMAGE) {
            nse_log("[nse] host build matches: %s", NSE_TARGET_DESC);
        } else {
            nse_log("[nse] ***********************************************************");
            nse_log("[nse] HOST BUILD DOES NOT MATCH.");
            nse_log("[nse]   expected  TimeDateStamp=%08lX SizeOfImage=%08lX  (%s)",
                    (unsigned long)NSE_TARGET_TIMESTAMP,
                    (unsigned long)NSE_TARGET_SIZEOFIMAGE, NSE_TARGET_DESC);
            nse_log("[nse]   found     TimeDateStamp=%08lX SizeOfImage=%08lX",
                    (unsigned long)stamp, (unsigned long)sizeimg);
            nse_log("[nse]   The Lua addresses below were derived for a DIFFERENT build");
            nse_log("[nse]   and are very unlikely to be right. Expect the hooks to be");
            nse_log("[nse]   refused on a prologue mismatch - that refusal is correct.");
            nse_log("[nse]   Recover with:  ruby tools/find_lua_api.rb --verify");
            nse_log("[nse]   then paste the new #defines into src/nse_proxy.c and rebuild.");
            nse_log("[nse] ***********************************************************");
        }
    }

    #define BIND(f, A) L_.f = (fn_##f)(A + g_delta)
    BIND(getfield,     A_lua_getfield);
    BIND(setfield,     A_lua_setfield);
    BIND(settop,       A_lua_settop);
    BIND(gettop,       A_lua_gettop);
    BIND(type,         A_lua_type);
    BIND(pushcclosure, A_lua_pushcclosure);
    BIND(pushlstring,  A_lua_pushlstring);
    BIND(tolstring,    A_lua_tolstring);
    BIND(loadbuffer,   A_luaL_loadbuffer);
    BIND(pcall,        A_lua_pcall);
    #undef BIND

    /* FIRST in the chain, so we see faults during our own eval before anything
     * else claims them. Disarmed except while pump() is actually running. */
    g_veh = AddVectoredExceptionHandler(1, nse_veh);
    nse_log("[nse] crash guard %s", g_veh ? "armed" : "FAILED to register");

    int ok = install_hook(A_lua_setfield, (void*)on_setfield);
    ok    &= install_hook(A_lua_getfield, (void*)on_getfield);
    if (!ok) {
        nse_log("[nse] hooks did not install - NSE is loaded but inert. "
                "The game will run normally.");
    }

    CreateThread(NULL, 0, pipe_thread, NULL, 0, NULL);
    nse_log("[nse] ready; pipe \\\\.\\pipe\\nse");
    return 0;
}

/* ========================= dinput8.dll proxying ========================== *
 * Forward the five real exports to the system DLL. Napoleon only actually calls
 * DirectInput8Create; the rest exist so nothing else that loads us breaks. */
static HMODULE g_real = NULL;
static void load_real(void) {
    char path[MAX_PATH];
    GetSystemDirectoryA(path, MAX_PATH);      /* SysWOW64 for a 32-bit process */
    strcat(path, "\\dinput8.dll");
    g_real = LoadLibraryA(path);
    if (!g_real) nse_log("[nse] FAILED to load the real dinput8 at %s", path);
}

typedef HRESULT (WINAPI *t_DI8Create)(HINSTANCE, DWORD, REFIID, LPVOID*, LPVOID);
typedef HRESULT (WINAPI *t_DllGetClassObject)(REFCLSID, REFIID, LPVOID*);
typedef HRESULT (WINAPI *t_void)(void);

/* NOTE: deliberately NO __declspec(dllexport) on these five.
 * Exports come solely from nse.def, which aliases the undecorated names onto
 * these stdcall-decorated symbols. Adding dllexport as well would ALSO export
 * the decorated "Name@N" forms, giving a double export table - and Napoleon
 * refuses to launch against a decorated dinput8. */
HRESULT WINAPI DirectInput8Create(
        HINSTANCE h, DWORD v, REFIID r, LPVOID* o, LPVOID u) {
    if (!g_real) load_real();
    t_DI8Create f = (t_DI8Create)GetProcAddress(g_real, "DirectInput8Create");
    return f ? f(h, v, r, o, u) : E_FAIL;
}
HRESULT WINAPI DllGetClassObject(REFCLSID c, REFIID r, LPVOID* o) {
    if (!g_real) load_real();
    t_DllGetClassObject f = (t_DllGetClassObject)GetProcAddress(g_real, "DllGetClassObject");
    return f ? f(c, r, o) : E_FAIL;
}
HRESULT WINAPI DllCanUnloadNow(void) {
    if (!g_real) load_real();
    t_void f = (t_void)GetProcAddress(g_real, "DllCanUnloadNow");
    return f ? f() : S_FALSE;
}
HRESULT WINAPI DllRegisterServer(void) {
    if (!g_real) load_real();
    t_void f = (t_void)GetProcAddress(g_real, "DllRegisterServer");
    return f ? f() : E_FAIL;
}
HRESULT WINAPI DllUnregisterServer(void) {
    if (!g_real) load_real();
    t_void f = (t_void)GetProcAddress(g_real, "DllUnregisterServer");
    return f ? f() : E_FAIL;
}

BOOL WINAPI DllMain(HINSTANCE hinst, DWORD reason, LPVOID reserved) {
    (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(hinst);
        load_real();
        /* Do NOT do real work inside DllMain (loader lock). Hand off to a
         * thread - which is also why the hooks land slightly after load rather
         * than during it, still long before Lua initialises. */
        CreateThread(NULL, 0, init_thread, NULL, 0, NULL);
    }
    return TRUE;
}
